from typing import Any, Protocol


class ExternalCatalogPort(Protocol):
    async def list_products(self, payload: Any = None) -> Any: ...
    async def list_branches(self, payload: dict[str, Any] | None = None) -> Any: ...


class ShopifyCatalogPort(Protocol):
    async def list_products(self, limit: int = 250) -> list[dict[str, Any]]: ...
    async def create_product(self, product: dict[str, Any]) -> dict[str, Any]: ...
    async def update_product(self, shopify_product_id: int, product: dict[str, Any]) -> dict[str, Any]: ...
    async def find_product_variant_by_sku(self, sku: str) -> tuple[dict[str, Any], dict[str, Any]] | None: ...
    async def ensure_collect(self, product_id: int, collection_id: int) -> dict[str, Any]: ...
    async def list_locations(self) -> list[dict[str, Any]]: ...
    async def create_location(self, location: dict[str, Any]) -> dict[str, Any]: ...


class IntegrationMappingPort(Protocol):
    async def start_sync_run(self, sync_type: str) -> Any: ...
    async def finish_sync_run(
        self,
        run: Any,
        status: str,
        stats: dict[str, Any] | None = None,
        error_message: str | None = None,
    ) -> Any: ...
    async def update_sync_run_stats(self, run: Any, stats: dict[str, Any]) -> Any: ...
    async def add_outbox_event(
        self,
        target: str,
        operation: str,
        payload: dict[str, Any],
        status: str = "pending",
    ) -> Any: ...
    async def get_sku_map_by_item_code(self, invitm_codigo: int) -> Any | None: ...
    async def get_sku_maps_by_item_codes(self, invitm_codigos: list[int]) -> dict[int, Any]: ...
    async def upsert_sku_map(self, **kwargs: Any) -> Any: ...
    async def get_family_map_by_name(self, se_familia_nombre: str) -> Any | None: ...
    async def upsert_branch_map(self, **kwargs: Any) -> Any: ...
